-- 03_annotations.sql — 유통 시연용 샘플 테이블·컬럼의 한국어 Display Annotation (PoC 3-B, 2026-09-30)
-- 정본은 web/src/lib/annotations.ts 의 RETAIL 세트다. 이 파일은 거기서 생성한 것 — 손으로 고치지 말고 ts 를 고친 뒤 다시 만든다.
-- ADD 는 덮어쓰지 않고 중복을 만들므로(개발노하우 3.3) 반드시 DROP 후 ADD. 앱의 「스키마·Annotation」 탭 적용/제거와 같은 내용.

ALTER TABLE ADMIN.POC_STORES ANNOTATIONS (DROP Display);
ALTER TABLE ADMIN.POC_STORES ANNOTATIONS (ADD Display '매장 마스터 - 제과 유통 매장(대형마트·편의점·슈퍼·온라인)');
ALTER TABLE ADMIN.POC_STORES MODIFY (STORE_ID ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_STORES MODIFY (STORE_ID ANNOTATIONS (ADD Display '매장 고유 식별자 (PK)'));
ALTER TABLE ADMIN.POC_STORES MODIFY (STORE_NAME ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_STORES MODIFY (STORE_NAME ANNOTATIONS (ADD Display '매장명'));
ALTER TABLE ADMIN.POC_STORES MODIFY (REGION ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_STORES MODIFY (REGION ANNOTATIONS (ADD Display '지역: 서울, 경기, 인천, 부산, 대구, 광주, 대전, 강원, 충청, 전라, 경상, 제주'));
ALTER TABLE ADMIN.POC_STORES MODIFY (CHANNEL ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_STORES MODIFY (CHANNEL ANNOTATIONS (ADD Display '유통 채널: 대형마트, 편의점, 슈퍼마켓, 온라인'));
ALTER TABLE ADMIN.POC_STORES MODIFY (OPEN_DATE ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_STORES MODIFY (OPEN_DATE ANNOTATIONS (ADD Display '개점일'));
ALTER TABLE ADMIN.POC_STORES MODIFY (STORE_SIZE_SQM ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_STORES MODIFY (STORE_SIZE_SQM ANNOTATIONS (ADD Display '매장 면적 (제곱미터)'));

ALTER TABLE ADMIN.POC_PRODUCTS ANNOTATIONS (DROP Display);
ALTER TABLE ADMIN.POC_PRODUCTS ANNOTATIONS (ADD Display '제품 마스터 - 제과 제품(비스킷·스낵·캔디·젤리·초콜릿)');
ALTER TABLE ADMIN.POC_PRODUCTS MODIFY (PRODUCT_ID ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_PRODUCTS MODIFY (PRODUCT_ID ANNOTATIONS (ADD Display '제품 고유 식별자 (PK)'));
ALTER TABLE ADMIN.POC_PRODUCTS MODIFY (PRODUCT_NAME ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_PRODUCTS MODIFY (PRODUCT_NAME ANNOTATIONS (ADD Display '제품명'));
ALTER TABLE ADMIN.POC_PRODUCTS MODIFY (CATEGORY ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_PRODUCTS MODIFY (CATEGORY ANNOTATIONS (ADD Display '제품 카테고리: 비스킷, 스낵, 캔디, 젤리, 초콜릿'));
ALTER TABLE ADMIN.POC_PRODUCTS MODIFY (UNIT_PRICE ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_PRODUCTS MODIFY (UNIT_PRICE ANNOTATIONS (ADD Display '단위 판매가 (원, KRW)'));
ALTER TABLE ADMIN.POC_PRODUCTS MODIFY (LAUNCH_DATE ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_PRODUCTS MODIFY (LAUNCH_DATE ANNOTATIONS (ADD Display '출시일'));
ALTER TABLE ADMIN.POC_PRODUCTS MODIFY (IS_NEW ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_PRODUCTS MODIFY (IS_NEW ANNOTATIONS (ADD Display '신제품 여부: Y=출시 1년 이내, N=기존 제품'));

ALTER TABLE ADMIN.POC_DISPLAYS ANNOTATIONS (DROP Display);
ALTER TABLE ADMIN.POC_DISPLAYS ANNOTATIONS (ADD Display '진열 현황 - 매장별 제품의 진열 위치·면수·전시 상태 조사 결과. DISPLAY_LOCATION 이 미입력인 행이 약 30% 있다 (데이터 품질 이슈)');
ALTER TABLE ADMIN.POC_DISPLAYS MODIFY (DISPLAY_ID ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_DISPLAYS MODIFY (DISPLAY_ID ANNOTATIONS (ADD Display '진열 조사 고유 식별자 (PK)'));
ALTER TABLE ADMIN.POC_DISPLAYS MODIFY (STORE_ID ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_DISPLAYS MODIFY (STORE_ID ANNOTATIONS (ADD Display '매장 ID (FK → POC_STORES)'));
ALTER TABLE ADMIN.POC_DISPLAYS MODIFY (PRODUCT_ID ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_DISPLAYS MODIFY (PRODUCT_ID ANNOTATIONS (ADD Display '제품 ID (FK → POC_PRODUCTS)'));
ALTER TABLE ADMIN.POC_DISPLAYS MODIFY (DISPLAY_LOCATION ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_DISPLAYS MODIFY (DISPLAY_LOCATION ANNOTATIONS (ADD Display '진열 위치(매대): 매장입구, 중앙통로, 계산대앞, 음료코너, 시식코너, 미입력. 미입력은 조사 누락이며 집계에서 제외해야 할 수 있다'));
ALTER TABLE ADMIN.POC_DISPLAYS MODIFY (FACE_COUNT ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_DISPLAYS MODIFY (FACE_COUNT ANNOTATIONS (ADD Display '진열 면수 - 매대에서 제품이 정면으로 보이는 칸 수 (1~6)'));
ALTER TABLE ADMIN.POC_DISPLAYS MODIFY (DISPLAY_STATE ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_DISPLAYS MODIFY (DISPLAY_STATE ANNOTATIONS (ADD Display '전시 상태: 단독(단독 진열), 혼합(타사 제품과 혼합 진열), 미입력'));
ALTER TABLE ADMIN.POC_DISPLAYS MODIFY (DISPLAY_POSITION ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_DISPLAYS MODIFY (DISPLAY_POSITION ANNOTATIONS (ADD Display '전시 위치(매대 안 위치): 전면중앙, 전면좌측, 전면우측, 상단, 하단'));
ALTER TABLE ADMIN.POC_DISPLAYS MODIFY (SURVEY_DATE ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_DISPLAYS MODIFY (SURVEY_DATE ANNOTATIONS (ADD Display '진열 조사일'));

ALTER TABLE ADMIN.POC_SALES ANNOTATIONS (DROP Display);
ALTER TABLE ADMIN.POC_SALES ANNOTATIONS (ADD Display '매출 - 일자별 매장별 제품별 판매 실적 (2025-10 ~ 2026-09, 약 6만 행)');
ALTER TABLE ADMIN.POC_SALES MODIFY (SALE_ID ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_SALES MODIFY (SALE_ID ANNOTATIONS (ADD Display '매출 고유 식별자 (PK)'));
ALTER TABLE ADMIN.POC_SALES MODIFY (SALE_DATE ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_SALES MODIFY (SALE_DATE ANNOTATIONS (ADD Display '판매 일자'));
ALTER TABLE ADMIN.POC_SALES MODIFY (STORE_ID ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_SALES MODIFY (STORE_ID ANNOTATIONS (ADD Display '매장 ID (FK → POC_STORES)'));
ALTER TABLE ADMIN.POC_SALES MODIFY (PRODUCT_ID ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_SALES MODIFY (PRODUCT_ID ANNOTATIONS (ADD Display '제품 ID (FK → POC_PRODUCTS)'));
ALTER TABLE ADMIN.POC_SALES MODIFY (QUANTITY ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_SALES MODIFY (QUANTITY ANNOTATIONS (ADD Display '판매 수량 (개)'));
ALTER TABLE ADMIN.POC_SALES MODIFY (AMOUNT ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_SALES MODIFY (AMOUNT ANNOTATIONS (ADD Display '매출 금액 (원, KRW) = 수량 × 단가 × (1 - 할인율)'));
ALTER TABLE ADMIN.POC_SALES MODIFY (PROMO_FLAG ANNOTATIONS (DROP Display));
ALTER TABLE ADMIN.POC_SALES MODIFY (PROMO_FLAG ANNOTATIONS (ADD Display '프로모션 적용 여부: Y=행사가 판매, N=정가 판매'));

-- 점검: 중복이 0행이어야 한다
SELECT object_name, column_name, COUNT(*) FROM user_annotations_usage WHERE object_name LIKE 'POC\_%' ESCAPE '\' AND annotation_name = 'DISPLAY' GROUP BY object_name, column_name HAVING COUNT(*) > 1;
